//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWindowsForm.ServicioWebJava {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WS.com/", ConfigurationName="ServicioWebJava.WebServiceMYSQL")]
    public interface WebServiceMYSQL {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.com/WebServiceMYSQL/helloRequest", ReplyAction="http://WS.com/WebServiceMYSQL/helloResponse")]
        ProyectoWindowsForm.ServicioWebJava.helloResponse hello(ProyectoWindowsForm.ServicioWebJava.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.com/WebServiceMYSQL/helloRequest", ReplyAction="http://WS.com/WebServiceMYSQL/helloResponse")]
        System.Threading.Tasks.Task<ProyectoWindowsForm.ServicioWebJava.helloResponse> helloAsync(ProyectoWindowsForm.ServicioWebJava.helloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.com/WebServiceMYSQL/ValidarRequest", ReplyAction="http://WS.com/WebServiceMYSQL/ValidarResponse")]
        ProyectoWindowsForm.ServicioWebJava.ValidarResponse Validar(ProyectoWindowsForm.ServicioWebJava.ValidarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.com/WebServiceMYSQL/ValidarRequest", ReplyAction="http://WS.com/WebServiceMYSQL/ValidarResponse")]
        System.Threading.Tasks.Task<ProyectoWindowsForm.ServicioWebJava.ValidarResponse> ValidarAsync(ProyectoWindowsForm.ServicioWebJava.ValidarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://WS.com/", Order=0)]
        public ProyectoWindowsForm.ServicioWebJava.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(ProyectoWindowsForm.ServicioWebJava.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://WS.com/", Order=0)]
        public ProyectoWindowsForm.ServicioWebJava.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(ProyectoWindowsForm.ServicioWebJava.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar", Namespace="http://WS.com/", Order=0)]
        public ProyectoWindowsForm.ServicioWebJava.ValidarRequestBody Body;
        
        public ValidarRequest() {
        }
        
        public ValidarRequest(ProyectoWindowsForm.ServicioWebJava.ValidarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ValidarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        public ValidarRequestBody() {
        }
        
        public ValidarRequestBody(string Usuario, string Pass) {
            this.Usuario = Usuario;
            this.Pass = Pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarResponse", Namespace="http://WS.com/", Order=0)]
        public ProyectoWindowsForm.ServicioWebJava.ValidarResponseBody Body;
        
        public ValidarResponse() {
        }
        
        public ValidarResponse(ProyectoWindowsForm.ServicioWebJava.ValidarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ValidarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public ValidarResponseBody() {
        }
        
        public ValidarResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMYSQLChannel : ProyectoWindowsForm.ServicioWebJava.WebServiceMYSQL, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMYSQLClient : System.ServiceModel.ClientBase<ProyectoWindowsForm.ServicioWebJava.WebServiceMYSQL>, ProyectoWindowsForm.ServicioWebJava.WebServiceMYSQL {
        
        public WebServiceMYSQLClient() {
        }
        
        public WebServiceMYSQLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMYSQLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMYSQLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMYSQLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoWindowsForm.ServicioWebJava.helloResponse ProyectoWindowsForm.ServicioWebJava.WebServiceMYSQL.hello(ProyectoWindowsForm.ServicioWebJava.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            ProyectoWindowsForm.ServicioWebJava.helloRequest inValue = new ProyectoWindowsForm.ServicioWebJava.helloRequest();
            inValue.Body = new ProyectoWindowsForm.ServicioWebJava.helloRequestBody();
            inValue.Body.name = name;
            ProyectoWindowsForm.ServicioWebJava.helloResponse retVal = ((ProyectoWindowsForm.ServicioWebJava.WebServiceMYSQL)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoWindowsForm.ServicioWebJava.helloResponse> ProyectoWindowsForm.ServicioWebJava.WebServiceMYSQL.helloAsync(ProyectoWindowsForm.ServicioWebJava.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoWindowsForm.ServicioWebJava.helloResponse> helloAsync(string name) {
            ProyectoWindowsForm.ServicioWebJava.helloRequest inValue = new ProyectoWindowsForm.ServicioWebJava.helloRequest();
            inValue.Body = new ProyectoWindowsForm.ServicioWebJava.helloRequestBody();
            inValue.Body.name = name;
            return ((ProyectoWindowsForm.ServicioWebJava.WebServiceMYSQL)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoWindowsForm.ServicioWebJava.ValidarResponse ProyectoWindowsForm.ServicioWebJava.WebServiceMYSQL.Validar(ProyectoWindowsForm.ServicioWebJava.ValidarRequest request) {
            return base.Channel.Validar(request);
        }
        
        public int Validar(string Usuario, string Pass) {
            ProyectoWindowsForm.ServicioWebJava.ValidarRequest inValue = new ProyectoWindowsForm.ServicioWebJava.ValidarRequest();
            inValue.Body = new ProyectoWindowsForm.ServicioWebJava.ValidarRequestBody();
            inValue.Body.Usuario = Usuario;
            inValue.Body.Pass = Pass;
            ProyectoWindowsForm.ServicioWebJava.ValidarResponse retVal = ((ProyectoWindowsForm.ServicioWebJava.WebServiceMYSQL)(this)).Validar(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoWindowsForm.ServicioWebJava.ValidarResponse> ProyectoWindowsForm.ServicioWebJava.WebServiceMYSQL.ValidarAsync(ProyectoWindowsForm.ServicioWebJava.ValidarRequest request) {
            return base.Channel.ValidarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoWindowsForm.ServicioWebJava.ValidarResponse> ValidarAsync(string Usuario, string Pass) {
            ProyectoWindowsForm.ServicioWebJava.ValidarRequest inValue = new ProyectoWindowsForm.ServicioWebJava.ValidarRequest();
            inValue.Body = new ProyectoWindowsForm.ServicioWebJava.ValidarRequestBody();
            inValue.Body.Usuario = Usuario;
            inValue.Body.Pass = Pass;
            return ((ProyectoWindowsForm.ServicioWebJava.WebServiceMYSQL)(this)).ValidarAsync(inValue);
        }
    }
}
